name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: |
        cd ./src
        dotnet restore

    - name: Build
      run: |
        cd ./src
        dotnet build --no-restore -c Release

    - name: Run Benchmarks
      timeout-minutes: 360
      run: |
        dotnet run --no-build -c Release --project ./tools/EvenireDB.Tools.Benchmark/EvenireDB.Tools.Benchmark.csproj -- --exporters JSON --filter EvenireDB.Benchmark*

    - name: Upload Benchmark Results
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          cd ./BenchmarkDotNet.Artifacts/results/
          az storage container create --name results --account-name saevenirebenchmarks --connection-string "${{ secrets.SA_CONN_STR }}" 
          az storage blob upload-batch --account-name saevenirebenchmarks --destination results --destination-path "${{ github.run_id }}" --pattern *.json --source . --connection-string "${{ secrets.SA_CONN_STR }}"
