name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: |
        cd ./src
        dotnet restore

    - name: Build
      run: |
        cd ./src
        dotnet build --no-restore -c Release

    - name: Run Benchmarks
      run: |
        dotnet run --no-build -c Release --project ./tools/EvenireDB.Tools.Benchmark/EvenireDB.Tools.Benchmark.csproj -- --exporters JSON --filter EvenireDB.Benchmark*