name: Benchmark

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: |
        cd ./src
        dotnet restore

    - name: Build
      run: |
        cd ./src
        dotnet build --no-restore -c Release

    - name: Test
      run: |
        cd ./src
        dotnet test ./EvenireDb.Tests.slnf --no-build -m:1 -s ../tests.runsettings
